# values.yaml

# ElasticSearch Ayarları
elasticsearch:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"

# Kibana Ayarları
kibana:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"